// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9rPwwrLTbAevEVaoFJQe4rVoZRSS4Y2k',
    appId: '1:33942020611:web:7594368b39765b86a8e436',
    messagingSenderId: '33942020611',
    projectId: 'astdafa-c350e',
    authDomain: 'astdafa-c350e.firebaseapp.com',
    storageBucket: 'astdafa-c350e.appspot.com',
    measurementId: 'G-2BHWXL25LV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJPibvNtVBqvOHLibOr1U68ZUsLwZ0ARg',
    appId: '1:33942020611:android:540f2b18b1bf81c9a8e436',
    messagingSenderId: '33942020611',
    projectId: 'astdafa-c350e',
    storageBucket: 'astdafa-c350e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUxC0LNzha35TK-B0hHi56weX6bUK2IZg',
    appId: '1:33942020611:ios:28d2dc157c52dad4a8e436',
    messagingSenderId: '33942020611',
    projectId: 'astdafa-c350e',
    storageBucket: 'astdafa-c350e.appspot.com',
    iosClientId: '33942020611-9q7pdich5i2bd6ihtikcv7cqv9t914l7.apps.googleusercontent.com',
    iosBundleId: 'com.example.astdafa',
  );
}
